android.nonTransitiveRClass=true
android.overridePathCheck=true
android.useAndroidX=true
kotlin.code.style=official
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
configurationApiBaseUrl=https://example.invalid/
serverJwtPublicKeyBase64=
serverJwtIssuer=rechi-mdm-api
serverJwtAudience=rechi-mdm-device
